### ISSUE TITLE
STC15L2K60S2

### ISSUE THREAD

**Issue by blindman2k** [nekromant/stcdude#6] opened 2015-01-20 01:15 UTC
Hi @nekromant,

I have been trying to use your awesome effort to program the STC15L2K60S2's I have here and they appear to be ever so slightly incompatible. Do you have any ideas on how to adjust stc-dude to work with this mcu?

**Comment by nekromant** [comment] 2015-01-20 12:12
What's the output? AFAIK I just programmed the very STC12C5A60S2 last week.

**Comment by MidnightWonderer** [comment] 2015-01-20 15:56
@blindman2k I can confirm successfully connection to that certain device. Double check your connection especially when you are using a breadboard. You can also tap the uart output for better visualization for what going on.

**Comment by nekromant** [comment] 2015-01-20 16:02
Try also different handshake baudrates. These tend to be messy on some crystals

**Comment by blindman2k** [comment] 2015-01-20 21:16
Hey guys and thanks for the quick responses. I have a fully formed PCB not a breadboard and I have a full debug trace of stc-isp for Windows running and it's flawless, both at 2400 and 115200 every time.
https://www.dropbox.com/s/72hx4ptwfk1f39o/program%20short.log (ignore my comments and snips).

I am getting a checksum error and a segfault at both 2400 and 115200.
Is there a debug/trace flag?

```
STC ISP Tool. (c) Necromant 2012
Loading lua script: /usr/local/share/stcdude/lua/init.lua
Using /dev/cu.usbserial-A703BXNC @ 115200
Power on target MCU at will
Checksum error, dropping packet!
Segmentation fault: 11
```

**Comment by nekromant** [comment] 2015-01-20 22:20
What OS are you running?

**Comment by blindman2k** [comment] 2015-01-20 22:20
Mac, latest version.

**Comment by nekromant** [comment] 2015-01-21 08:15
I haven't tested stcdude on mac, so this might be the problem by itself. I'll give a code a quick look to see what could have segfaulted. Meanwhile, can you compile it with -g and use gdb to get a backtrace? 
I can't reproduce this myself, since I don't have a mac around (and am too lazy to install hackintosh).

**Comment by blindman2k** [comment] 2015-01-21 08:30
I have no issue with laziness :)
I am stuck until Monday as I am not in the office and the hardware is.

**Comment by blindman2k** [comment] 2015-01-27 01:01
gdb dump is below.
```
STC ISP Tool. (c) Necromant 2012
Loading lua script: /usr/local/share/stcdude/lua/init.lua
Using /dev/cu.usbserial-A703BXNC @ 115200
Power on target MCU at will
Checksum error, dropping packet!

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x0000000000000008
parse_info_packet (L=0x100104c20, pck=0x0, baudrate=115200) at payload.c:183
183		struct info_packet *inf = (struct info_packet *) pck->data;
```

**Comment by blindman2k** [comment] 2015-02-02 04:12
Hey Nekro,

Did that assist you at all. I am under a bit of pressure to get this completed. Someone else suggested this was a STC15 device not a STC12. What does that change?

Thanks!

**Comment by nekromant** [comment] 2015-02-03 19:41
Sorry for the delay, I couldn't find a spare minute to have a close look at it. 
It looks like it doesn't handle things properly if a packet with an invalid checksum arrives. This should be fixed now. See if it works. But if STC15L uses different checksumming - well, we're screwed and more reverse-engineering is needed.

**Comment by blindman2k** [comment] 2015-02-03 21:13
Yep, it doesn't crash now. It just responds "Checksum error, dropping packet!"
Thanks for your effort, it is appreciated.

**Comment by nekromant** [comment] 2015-02-03 22:10
See if the other 'stc-isp' tool works for you, If it does - I'll see if I can add some functionality from it. It's hard to do anything without the actual device on your bench.

**Comment by blindman2k** [comment] 2015-02-03 22:12
Yep, I am working with them too. The most promising is
https://github.com/grigorig/stcgal which has specific support for the STC15
protocol but doesn't quite work.

**Closed** 2016-02-09 10:18 UTC
